Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.167.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'UserMultiRoleAssignmentViewDataFormUSERSLIST' data form
''' </summary>
Partial Public Class [UserMultiRoleAssignmentViewDataFormUSERSLISTUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _userid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _username As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _numberofroles As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public Sub New()
        MyBase.New()

        _userid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _username = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _numberofroles = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

        '
        '_userid
        '
        _userid.Name = "USERID"
        _userid.Caption = "USERID"
        _userid.Visible = False
        _userid.DBReadOnly = True
        Me.Fields.Add(_userid)
        '
        '_username
        '
        _username.Name = "USERNAME"
        _username.Caption = "Application User"
        _username.DBReadOnly = True
        Me.Fields.Add(_username)
        '
        '_numberofroles
        '
        _numberofroles.Name = "NUMBEROFROLES"
        _numberofroles.Caption = "Role #"
        _numberofroles.DBReadOnly = True
        Me.Fields.Add(_numberofroles)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [USERID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _userid
        End Get
    End Property
    
    ''' <summary>
    ''' Application User
    ''' </summary>
    <System.ComponentModel.Description("Application User")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [USERNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _username
        End Get
    End Property
    
    ''' <summary>
    ''' Role #
    ''' </summary>
    <System.ComponentModel.Description("Role #")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [NUMBEROFROLES]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _numberofroles
        End Get
    End Property
    
End Class
