Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.167.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'UserMultiRoleAssignmentViewDataFormROLELIST' data form
''' </summary>
Partial Public Class [UserMultiRoleAssignmentViewDataFormROLELISTUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _roleid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _rolename As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _numberofusers As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public Sub New()
        MyBase.New()

        _roleid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _rolename = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _numberofusers = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

        '
        '_roleid
        '
        _roleid.Name = "ROLEID"
        _roleid.Caption = "ROLEID"
        _roleid.Visible = False
        _roleid.DBReadOnly = True
        Me.Fields.Add(_roleid)
        '
        '_rolename
        '
        _rolename.Name = "ROLENAME"
        _rolename.Caption = "System Role"
        _rolename.DBReadOnly = True
        Me.Fields.Add(_rolename)
        '
        '_numberofusers
        '
        _numberofusers.Name = "NUMBEROFUSERS"
        _numberofusers.Caption = "User #"
        _numberofusers.DBReadOnly = True
        Me.Fields.Add(_numberofusers)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [ROLEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _roleid
        End Get
    End Property
    
    ''' <summary>
    ''' System Role
    ''' </summary>
    <System.ComponentModel.Description("System Role")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [ROLENAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _rolename
        End Get
    End Property
    
    ''' <summary>
    ''' User #
    ''' </summary>
    <System.ComponentModel.Description("User #")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [NUMBEROFUSERS]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _numberofusers
        End Get
    End Property
    
End Class
